# Spring Application
spring.application.name=quiz_2_III

# Database Configuration
spring.r2dbc.url=r2dbc:postgresql://localhost:5433/quiz_db
spring.r2dbc.username=user
spring.r2dbc.password=1234
spring.sql.init.mode=always

# JWT Configuration
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000
